import { Poppins } from "next/font/google";
import "./globals.css";
import { Providers } from "./provider";
const poppins = Poppins({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Airbnb Search",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Providers>
      <html lang="en">
        <body className={poppins.className}>{children}</body>
      </html>
    </Providers>
  );
}
